! CALCULATES ORIENTATION CORRELATION FUNCTION (OCF)
! NEEDS TRAJECTORY FILE, INDEX OF MOLECULE
! OUTPUT ANGLE EVOLUTION, VECTOR WITH Z

PROGRAM  OCF_SINGLE_MOL
  IMPLICIT NONE
  INTEGER:: NATOM, HEAD, TAIL, NTRAJ, NSKIP, ATOM_A, ATOM_B, I, J,K,&
			TRAJ_COUNT, COL_SKIP
  INTEGER, ALLOCATABLE:: STAT_COUNT(:)
  REAL*8 :: REF_VEC(3),RIJ(3),PI, ANG, RIJA(3), RIJB(3), DIR_VEC(3)
  REAL*8, ALLOCATABLE, DIMENSION(:):: RAW_ANG, TEMPJ,&
  DIR_VECX,DIR_VECY,DIR_VECZ
  CHARACTER*50:: TRAJFILE

  OPEN(21,FILE="input_ocf_single_mol.dat",STATUS='OLD')
    READ(21,*) TRAJFILE, HEAD, TAIL, COL_SKIP
    READ(21,*) NTRAJ, NSKIP 
    READ(21,*) NATOM
    READ(21,*) ATOM_A, ATOM_B
  CLOSE(21)
  NSKIP = NSKIP * (HEAD + NATOM + TAIL)
  ALLOCATE(TEMPJ(COL_SKIP), DIR_VECX(NTRAJ), DIR_VECY(NTRAJ), DIR_VECZ(NTRAJ),&
           STAT_COUNT(NTRAJ), RAW_ANG(NTRAJ) )
  IF (ATOM_B<ATOM_A) THEN
    REF_VEC = -REF_VEC
    I=ATOM_B
    ATOM_B=ATOM_A
    ATOM_A=I
  END IF     
  OPEN(22,FILE=TRIM(TRAJFILE),STATUS='OLD')
  DO TRAJ_COUNT = 1, NTRAJ
    DO I = 1, HEAD
      READ(22,*)
    END DO
    DO I =1, ATOM_A-1
      READ(22,*)
    END DO
    READ(22,*) (TEMPJ(J), J=1,COL_SKIP), (RIJA(J), J= 1, 3)
    DO I=ATOM_A+1, ATOM_B-1
      READ(22,*)
    END DO
    READ(22,*) (TEMPJ(J), J=1,COL_SKIP), (RIJB(J), J= 1, 3)
    DO I = ATOM_B+1, NATOM+TAIL 
      READ(22,*) 
    END DO
    DO I = 1, NSKIP
      READ(22,*) ! SKIP
    END DO
    DIR_VEC = RIJB-RIJA
    DIR_VECX(TRAJ_COUNT)=DIR_VEC(1)
    DIR_VECY(TRAJ_COUNT)=DIR_VEC(2)
    DIR_VECZ(TRAJ_COUNT)=DIR_VEC(3)
  END DO
  CLOSE(22)
  RAW_ANG    = 0.0D0
  STAT_COUNT = 0
  DO TRAJ_COUNT=1, NTRAJ
    REF_VEC(1)=DIR_VECX(TRAJ_COUNT)
    REF_VEC(2)=DIR_VECY(TRAJ_COUNT)
    REF_VEC(3)=DIR_VECZ(TRAJ_COUNT)    
    DO J = TRAJ_COUNT+1,NTRAJ
       K= J-TRAJ_COUNT
       DIR_VEC(1)=DIR_VECX(J)
       DIR_VEC(2)=DIR_VECY(J)
       DIR_VEC(3)=DIR_VECZ(J)       
       RAW_ANG(K)=RAW_ANG(K) + DOT_PRODUCT(DIR_VEC, REF_VEC)/&
       DSQRT(DOT_PRODUCT(REF_VEC, REF_VEC)*DOT_PRODUCT(DIR_VEC,DIR_VEC))
       STAT_COUNT(K)=STAT_COUNT(K)+1
    END DO
  END DO
  OPEN(32,FILE="Ocf_out.dat")
  WRITE(32,*) "# TRAJ,  <COS(THETA)>, #Data_set"
  DO I = 1, NTRAJ
    J= STAT_COUNT(I)
    IF(J==0) CYCLE
    WRITE(32,*)  I, RAW_ANG(I)/DBLE(J), J
  END DO 
  
  CLOSE(32)
  

END PROGRAM OCF_SINGLE_MOL

